# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/whole/whole.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole || ORIG_REF_NAME==whole} -quiet] -quiet

# IP: bd/whole/ip/whole_alu4_wrapper_0_0/whole_alu4_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_alu4_wrapper_0_0 || ORIG_REF_NAME==whole_alu4_wrapper_0_0} -quiet] -quiet

# IP: bd/whole/ip/whole_alu4_wrapper_0_1/whole_alu4_wrapper_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_alu4_wrapper_0_1 || ORIG_REF_NAME==whole_alu4_wrapper_0_1} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_0_0/whole_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_0_0 || ORIG_REF_NAME==whole_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_0_1/whole_util_vector_logic_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_0_1 || ORIG_REF_NAME==whole_util_vector_logic_0_1} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_0_2/whole_util_vector_logic_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_0_2 || ORIG_REF_NAME==whole_util_vector_logic_0_2} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_0_3/whole_util_vector_logic_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_0_3 || ORIG_REF_NAME==whole_util_vector_logic_0_3} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_3_0/whole_util_vector_logic_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_3_0 || ORIG_REF_NAME==whole_util_vector_logic_3_0} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_3_1/whole_util_vector_logic_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_3_1 || ORIG_REF_NAME==whole_util_vector_logic_3_1} -quiet] -quiet

# IP: bd/whole/ip/whole_alu4_wrapper_1_0/whole_alu4_wrapper_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_alu4_wrapper_1_0 || ORIG_REF_NAME==whole_alu4_wrapper_1_0} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_2_0/whole_util_vector_logic_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_2_0 || ORIG_REF_NAME==whole_util_vector_logic_2_0} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_6_0/whole_util_vector_logic_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_6_0 || ORIG_REF_NAME==whole_util_vector_logic_6_0} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_6_1/whole_util_vector_logic_6_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_6_1 || ORIG_REF_NAME==whole_util_vector_logic_6_1} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_5_0/whole_util_vector_logic_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_5_0 || ORIG_REF_NAME==whole_util_vector_logic_5_0} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_5_1/whole_util_vector_logic_5_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_5_1 || ORIG_REF_NAME==whole_util_vector_logic_5_1} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_5_2/whole_util_vector_logic_5_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_5_2 || ORIG_REF_NAME==whole_util_vector_logic_5_2} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_8_0/whole_util_vector_logic_8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_8_0 || ORIG_REF_NAME==whole_util_vector_logic_8_0} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_11_0/whole_util_vector_logic_11_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_11_0 || ORIG_REF_NAME==whole_util_vector_logic_11_0} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_13_0/whole_util_vector_logic_13_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_13_0 || ORIG_REF_NAME==whole_util_vector_logic_13_0} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_13_1/whole_util_vector_logic_13_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_13_1 || ORIG_REF_NAME==whole_util_vector_logic_13_1} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_13_2/whole_util_vector_logic_13_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_13_2 || ORIG_REF_NAME==whole_util_vector_logic_13_2} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_13_3/whole_util_vector_logic_13_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_13_3 || ORIG_REF_NAME==whole_util_vector_logic_13_3} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_13_4/whole_util_vector_logic_13_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_13_4 || ORIG_REF_NAME==whole_util_vector_logic_13_4} -quiet] -quiet

# IP: bd/whole/ip/whole_counter_0_0/whole_counter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_counter_0_0 || ORIG_REF_NAME==whole_counter_0_0} -quiet] -quiet

# XDC: bd/whole/whole_ooc.xdc
