# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/new.xdc

# Block Designs: bd/whole/whole.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole || ORIG_REF_NAME==whole} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_0_0/whole_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_0_0 || ORIG_REF_NAME==whole_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_0_1/whole_util_vector_logic_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_0_1 || ORIG_REF_NAME==whole_util_vector_logic_0_1} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_0_2/whole_util_vector_logic_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_0_2 || ORIG_REF_NAME==whole_util_vector_logic_0_2} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_0_3/whole_util_vector_logic_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_0_3 || ORIG_REF_NAME==whole_util_vector_logic_0_3} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_3_0/whole_util_vector_logic_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_3_0 || ORIG_REF_NAME==whole_util_vector_logic_3_0} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_3_1/whole_util_vector_logic_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_3_1 || ORIG_REF_NAME==whole_util_vector_logic_3_1} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_2_0/whole_util_vector_logic_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_2_0 || ORIG_REF_NAME==whole_util_vector_logic_2_0} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_6_0/whole_util_vector_logic_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_6_0 || ORIG_REF_NAME==whole_util_vector_logic_6_0} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_6_1/whole_util_vector_logic_6_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_6_1 || ORIG_REF_NAME==whole_util_vector_logic_6_1} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_5_0/whole_util_vector_logic_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_5_0 || ORIG_REF_NAME==whole_util_vector_logic_5_0} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_5_1/whole_util_vector_logic_5_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_5_1 || ORIG_REF_NAME==whole_util_vector_logic_5_1} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_5_2/whole_util_vector_logic_5_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_5_2 || ORIG_REF_NAME==whole_util_vector_logic_5_2} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_8_0/whole_util_vector_logic_8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_8_0 || ORIG_REF_NAME==whole_util_vector_logic_8_0} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_11_0/whole_util_vector_logic_11_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_11_0 || ORIG_REF_NAME==whole_util_vector_logic_11_0} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_13_0/whole_util_vector_logic_13_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_13_0 || ORIG_REF_NAME==whole_util_vector_logic_13_0} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_13_1/whole_util_vector_logic_13_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_13_1 || ORIG_REF_NAME==whole_util_vector_logic_13_1} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_13_2/whole_util_vector_logic_13_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_13_2 || ORIG_REF_NAME==whole_util_vector_logic_13_2} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_13_3/whole_util_vector_logic_13_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_13_3 || ORIG_REF_NAME==whole_util_vector_logic_13_3} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_13_4/whole_util_vector_logic_13_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_13_4 || ORIG_REF_NAME==whole_util_vector_logic_13_4} -quiet] -quiet

# IP: bd/whole/ip/whole_Clock_0_0/whole_Clock_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_Clock_0_0 || ORIG_REF_NAME==whole_Clock_0_0} -quiet] -quiet

# IP: bd/whole/ip/whole_two_three_0_0/whole_two_three_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_two_three_0_0 || ORIG_REF_NAME==whole_two_three_0_0} -quiet] -quiet

# IP: bd/whole/ip/whole_two_three_0_1/whole_two_three_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_two_three_0_1 || ORIG_REF_NAME==whole_two_three_0_1} -quiet] -quiet

# IP: bd/whole/ip/whole_decoder_0_0/whole_decoder_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_decoder_0_0 || ORIG_REF_NAME==whole_decoder_0_0} -quiet] -quiet

# IP: bd/whole/ip/whole_counter_1_0/whole_counter_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_counter_1_0 || ORIG_REF_NAME==whole_counter_1_0} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_0_9/whole_util_vector_logic_0_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_0_9 || ORIG_REF_NAME==whole_util_vector_logic_0_9} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_3_3/whole_util_vector_logic_3_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_3_3 || ORIG_REF_NAME==whole_util_vector_logic_3_3} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_25_0/whole_util_vector_logic_25_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_25_0 || ORIG_REF_NAME==whole_util_vector_logic_25_0} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_25_1/whole_util_vector_logic_25_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_25_1 || ORIG_REF_NAME==whole_util_vector_logic_25_1} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_25_2/whole_util_vector_logic_25_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_25_2 || ORIG_REF_NAME==whole_util_vector_logic_25_2} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_25_3/whole_util_vector_logic_25_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_25_3 || ORIG_REF_NAME==whole_util_vector_logic_25_3} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_25_4/whole_util_vector_logic_25_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_25_4 || ORIG_REF_NAME==whole_util_vector_logic_25_4} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_24_0/whole_util_vector_logic_24_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_24_0 || ORIG_REF_NAME==whole_util_vector_logic_24_0} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_13_5/whole_util_vector_logic_13_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_13_5 || ORIG_REF_NAME==whole_util_vector_logic_13_5} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_13_6/whole_util_vector_logic_13_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_13_6 || ORIG_REF_NAME==whole_util_vector_logic_13_6} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_13_7/whole_util_vector_logic_13_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_13_7 || ORIG_REF_NAME==whole_util_vector_logic_13_7} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_25_5/whole_util_vector_logic_25_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_25_5 || ORIG_REF_NAME==whole_util_vector_logic_25_5} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_25_6/whole_util_vector_logic_25_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_25_6 || ORIG_REF_NAME==whole_util_vector_logic_25_6} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_25_7/whole_util_vector_logic_25_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_25_7 || ORIG_REF_NAME==whole_util_vector_logic_25_7} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_24_1/whole_util_vector_logic_24_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_24_1 || ORIG_REF_NAME==whole_util_vector_logic_24_1} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_19_0/whole_util_vector_logic_19_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_19_0 || ORIG_REF_NAME==whole_util_vector_logic_19_0} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_19_1/whole_util_vector_logic_19_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_19_1 || ORIG_REF_NAME==whole_util_vector_logic_19_1} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_33_0/whole_util_vector_logic_33_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_33_0 || ORIG_REF_NAME==whole_util_vector_logic_33_0} -quiet] -quiet

# IP: bd/whole/ip/whole_util_vector_logic_33_1/whole_util_vector_logic_33_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==whole_util_vector_logic_33_1 || ORIG_REF_NAME==whole_util_vector_logic_33_1} -quiet] -quiet

# XDC: bd/whole/whole_ooc.xdc
