# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a35tcsg324-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/light/alu4.cache/wt [current_project]
set_property parent.project_path D:/light/alu4.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  c:/Users/think/Desktop
  c:/Users/think/Desktop/two_four/two_four.srcs/sources_1/new
  c:/Users/think/Desktop/three_seven_new/three_seven_new.srcs/sources_1/new
  c:/Users/think/Desktop/project_13/project_13.srcs
  d:/devision/devision.srcs/sources_1/new
  d:/devision/devision.srcs
  c:/Users/think/Desktop/counter/counter.srcs/sources_1/new
} [current_project]
set_property ip_output_repo d:/light/alu4.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib D:/light/alu4.srcs/sources_1/bd/whole/hdl/whole_wrapper.v
add_files D:/light/alu4.srcs/sources_1/bd/whole/whole.bd
set_property used_in_implementation false [get_files -all D:/light/alu4.srcs/sources_1/bd/whole/whole_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/light/alu4.srcs/constrs_1/new/new.xdc
set_property used_in_implementation false [get_files D:/light/alu4.srcs/constrs_1/new/new.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top whole_wrapper -part xc7a35tcsg324-3


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef whole_wrapper.dcp
create_report "synth_2_synth_report_utilization_0" "report_utilization -file whole_wrapper_utilization_synth.rpt -pb whole_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
