# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a35tcsg324-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/admin/Desktop/counter_new/counter_new.cache/wt [current_project]
set_property parent.project_path C:/Users/admin/Desktop/counter_new/counter_new.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/admin/Desktop/counter_new/counter_new.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/admin/Desktop/counter_new/counter_new.srcs/sources_1/new/JK.v
  C:/Users/admin/Desktop/counter_new/counter_new.srcs/sources_1/new/clk.v
  C:/Users/admin/Desktop/counter_new/counter_new.srcs/sources_1/new/counter.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/admin/Desktop/counter_new/counter_new.srcs/constrs_1/new/counter_xdc.xdc
set_property used_in_implementation false [get_files C:/Users/admin/Desktop/counter_new/counter_new.srcs/constrs_1/new/counter_xdc.xdc]


synth_design -top counter -part xc7a35tcsg324-3


write_checkpoint -force -noxdef counter.dcp

catch { report_utilization -file counter_utilization_synth.rpt -pb counter_utilization_synth.pb }
