#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2018.1 (64-bit)
#
# Filename    : whole.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Wed Jun 20 20:32:27 +0800 2018
# SW Build 2188600 on Wed Apr  4 18:40:38 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved. 
#
# usage: whole.sh [-help]
# usage: whole.sh [-lib_map_path]
# usage: whole.sh [-noclean_files]
# usage: whole.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'whole.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(util_vector_logic_v2_0_1 xil_defaultlib)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "whole.sh - Script generated by export_simulation (Vivado v2018.1 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work util_vector_logic_v2_0_1 $vlogan_opts +v2k \
    "$ref_dir/../../../../alu4.srcs/sources_1/bd/whole/ipshared/2137/hdl/util_vector_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../bd/whole/ip/whole_util_vector_logic_0_0/sim/whole_util_vector_logic_0_0.v" \
    "$ref_dir/../../../bd/whole/ip/whole_util_vector_logic_0_1/sim/whole_util_vector_logic_0_1.v" \
    "$ref_dir/../../../bd/whole/ip/whole_util_vector_logic_0_2/sim/whole_util_vector_logic_0_2.v" \
    "$ref_dir/../../../bd/whole/ip/whole_util_vector_logic_0_3/sim/whole_util_vector_logic_0_3.v" \
    "$ref_dir/../../../bd/whole/ip/whole_util_vector_logic_3_0/sim/whole_util_vector_logic_3_0.v" \
    "$ref_dir/../../../bd/whole/ip/whole_util_vector_logic_3_1/sim/whole_util_vector_logic_3_1.v" \
    "$ref_dir/../../../bd/whole/ip/whole_util_vector_logic_2_0/sim/whole_util_vector_logic_2_0.v" \
    "$ref_dir/../../../bd/whole/ip/whole_util_vector_logic_6_0/sim/whole_util_vector_logic_6_0.v" \
    "$ref_dir/../../../bd/whole/ip/whole_util_vector_logic_6_1/sim/whole_util_vector_logic_6_1.v" \
    "$ref_dir/../../../bd/whole/ip/whole_util_vector_logic_5_0/sim/whole_util_vector_logic_5_0.v" \
    "$ref_dir/../../../bd/whole/ip/whole_util_vector_logic_5_1/sim/whole_util_vector_logic_5_1.v" \
    "$ref_dir/../../../bd/whole/ip/whole_util_vector_logic_5_2/sim/whole_util_vector_logic_5_2.v" \
    "$ref_dir/../../../bd/whole/ip/whole_util_vector_logic_8_0/sim/whole_util_vector_logic_8_0.v" \
    "$ref_dir/../../../bd/whole/ip/whole_util_vector_logic_11_0/sim/whole_util_vector_logic_11_0.v" \
    "$ref_dir/../../../bd/whole/ip/whole_util_vector_logic_13_0/sim/whole_util_vector_logic_13_0.v" \
    "$ref_dir/../../../bd/whole/ip/whole_util_vector_logic_13_1/sim/whole_util_vector_logic_13_1.v" \
    "$ref_dir/../../../bd/whole/ip/whole_util_vector_logic_13_2/sim/whole_util_vector_logic_13_2.v" \
    "$ref_dir/../../../bd/whole/ip/whole_util_vector_logic_13_3/sim/whole_util_vector_logic_13_3.v" \
    "$ref_dir/../../../bd/whole/ip/whole_util_vector_logic_13_4/sim/whole_util_vector_logic_13_4.v" \
    "$ref_dir/../../../bd/whole/sim/whole.v" \
    "$ref_dir/../../../bd/whole/ipshared/e29d/sources_1/new/Clock.v" \
    "$ref_dir/../../../bd/whole/ip/whole_Clock_0_0/sim/whole_Clock_0_0.v" \
    "$ref_dir/../../../../../Users/think/Desktop/two_four/two_four.srcs/sources_1/new/two_three.v" \
    "$ref_dir/../../../bd/whole/ip/whole_two_three_0_0/sim/whole_two_three_0_0.v" \
    "$ref_dir/../../../bd/whole/ip/whole_two_three_0_1/sim/whole_two_three_0_1.v" \
    "$ref_dir/../../../../../Users/think/Desktop/three_seven_new/three_seven_new.srcs/sources_1/new/decoder.v" \
    "$ref_dir/../../../bd/whole/ip/whole_decoder_0_0/sim/whole_decoder_0_0.v" \
    "$ref_dir/../../../../../Users/think/Desktop/counter/counter.srcs/sources_1/new/counter.v" \
    "$ref_dir/../../../bd/whole/ip/whole_counter_1_0/sim/whole_counter_1_0.v" \
    "$ref_dir/../../../bd/whole/ip/whole_util_vector_logic_0_9/sim/whole_util_vector_logic_0_9.v" \
    "$ref_dir/../../../bd/whole/ip/whole_util_vector_logic_3_3/sim/whole_util_vector_logic_3_3.v" \
    "$ref_dir/../../../bd/whole/ip/whole_util_vector_logic_25_0/sim/whole_util_vector_logic_25_0.v" \
    "$ref_dir/../../../bd/whole/ip/whole_util_vector_logic_25_1/sim/whole_util_vector_logic_25_1.v" \
    "$ref_dir/../../../bd/whole/ip/whole_util_vector_logic_25_2/sim/whole_util_vector_logic_25_2.v" \
    "$ref_dir/../../../bd/whole/ip/whole_util_vector_logic_25_3/sim/whole_util_vector_logic_25_3.v" \
    "$ref_dir/../../../bd/whole/ip/whole_util_vector_logic_25_4/sim/whole_util_vector_logic_25_4.v" \
    "$ref_dir/../../../bd/whole/ip/whole_util_vector_logic_24_0/sim/whole_util_vector_logic_24_0.v" \
    "$ref_dir/../../../bd/whole/ip/whole_util_vector_logic_13_5/sim/whole_util_vector_logic_13_5.v" \
    "$ref_dir/../../../bd/whole/ip/whole_util_vector_logic_13_6/sim/whole_util_vector_logic_13_6.v" \
    "$ref_dir/../../../bd/whole/ip/whole_util_vector_logic_13_7/sim/whole_util_vector_logic_13_7.v" \
    "$ref_dir/../../../bd/whole/ip/whole_util_vector_logic_25_5/sim/whole_util_vector_logic_25_5.v" \
    "$ref_dir/../../../bd/whole/ip/whole_util_vector_logic_25_6/sim/whole_util_vector_logic_25_6.v" \
    "$ref_dir/../../../bd/whole/ip/whole_util_vector_logic_25_7/sim/whole_util_vector_logic_25_7.v" \
    "$ref_dir/../../../bd/whole/ip/whole_util_vector_logic_24_1/sim/whole_util_vector_logic_24_1.v" \
    "$ref_dir/../../../bd/whole/ip/whole_util_vector_logic_19_0/sim/whole_util_vector_logic_19_0.v" \
    "$ref_dir/../../../bd/whole/ip/whole_util_vector_logic_19_1/sim/whole_util_vector_logic_19_1.v" \
    "$ref_dir/../../../bd/whole/ip/whole_util_vector_logic_33_0/sim/whole_util_vector_logic_33_0.v" \
    "$ref_dir/../../../bd/whole/ip/whole_util_vector_logic_33_1/sim/whole_util_vector_logic_33_1.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.whole xil_defaultlib.glbl -o whole_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./whole_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./whole.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key whole_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc whole_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./whole.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: whole.sh [-help]\n\
Usage: whole.sh [-lib_map_path]\n\
Usage: whole.sh [-reset_run]\n\
Usage: whole.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
